alter table "public"."active_movies" add column "entity_id" integer generated by default as identity not null;

CREATE UNIQUE INDEX active_movies_pkey ON public.active_movies USING btree (entity_id);

alter table "public"."active_movies" add constraint "active_movies_pkey" PRIMARY KEY using index "active_movies_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.count_votes()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
AS $function$update active_movies 
set votes =
(
  select count(*) from user_votes 
  where user_votes.voted_movie = active_movies.movie_id
)
where entity_id > 0$function$
;


